[package]
authors = ["huntc <huntchr@gmail.com>"]
edition = "2018"
readme = "README.md"
name = "app"
version = "0.1.0"

[dependencies]
lorawan-encoding = { version = "0.6.2", default-features = false, features = [ "default-crypto" ] }
